// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FG_cpp
arma::mat FG_cpp(const Rcpp::List& cov_Group, int L, int P, int M);
RcppExport SEXP _capp_FG_cpp(SEXP cov_GroupSEXP, SEXP LSEXP, SEXP PSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cov_Group(cov_GroupSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(FG_cpp(cov_Group, L, P, M));
    return rcpp_result_gen;
END_RCPP
}
// cap_solve
arma::mat cap_solve(const arma::mat& X);
RcppExport SEXP _capp_cap_solve(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cap_solve(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_capp_FG_cpp", (DL_FUNC) &_capp_FG_cpp, 4},
    {"_capp_cap_solve", (DL_FUNC) &_capp_cap_solve, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_capp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
