// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FG_cpp
arma::mat FG_cpp(const arma::cube& S_cube, const arma::vec& nval, const int max_iter, const double epsilon);
RcppExport SEXP _capr_FG_cpp(SEXP S_cubeSEXP, SEXP nvalSEXP, SEXP max_iterSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type S_cube(S_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nval(nvalSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(FG_cpp(S_cube, nval, max_iter, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// FG2_cpp
arma::mat FG2_cpp(const arma::cube& cov_cube, int maxit, int P, int M);
RcppExport SEXP _capr_FG2_cpp(SEXP cov_cubeSEXP, SEXP maxitSEXP, SEXP PSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type cov_cube(cov_cubeSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(FG2_cpp(cov_cube, maxit, P, M));
    return rcpp_result_gen;
END_RCPP
}
// CAP_one_component_unconstrained
Rcpp::List CAP_one_component_unconstrained(const arma::cube& S, const arma::mat& X, const arma::vec& T, arma::vec beta0, arma::vec gamma0, int max_iter, double tol);
RcppExport SEXP _capr_CAP_one_component_unconstrained(SEXP SSEXP, SEXP XSEXP, SEXP TSEXP, SEXP beta0SEXP, SEXP gamma0SEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(CAP_one_component_unconstrained(S, X, T, beta0, gamma0, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// CAP_one_component
Rcpp::List CAP_one_component(const arma::cube& S, const arma::mat& X, const arma::vec& T, arma::vec beta0, arma::vec gamma0, const arma::mat& Gamma_prev, int max_iter, double tol);
RcppExport SEXP _capr_CAP_one_component(SEXP SSEXP, SEXP XSEXP, SEXP TSEXP, SEXP beta0SEXP, SEXP gamma0SEXP, SEXP Gamma_prevSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Gamma_prev(Gamma_prevSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(CAP_one_component(S, X, T, beta0, gamma0, Gamma_prev, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// CAP_multi_components
Rcpp::List CAP_multi_components(const arma::cube& S, const arma::mat& X, const arma::vec& T, const int K, const arma::mat& Binit, const arma::mat& Gammainit, const bool orth, const int max_iter, const double tol);
RcppExport SEXP _capr_CAP_multi_components(SEXP SSEXP, SEXP XSEXP, SEXP TSEXP, SEXP KSEXP, SEXP BinitSEXP, SEXP GammainitSEXP, SEXP orthSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Binit(BinitSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Gammainit(GammainitSEXP);
    Rcpp::traits::input_parameter< const bool >::type orth(orthSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(CAP_multi_components(S, X, T, K, Binit, Gammainit, orth, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// cosine_similarity_cpp
double cosine_similarity_cpp(const arma::vec& a, const arma::vec& b, double eps);
RcppExport SEXP _capr_cosine_similarity_cpp(SEXP aSEXP, SEXP bSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_similarity_cpp(a, b, eps));
    return rcpp_result_gen;
END_RCPP
}
// log_deviation_from_diagonality_cpp
double log_deviation_from_diagonality_cpp(const arma::cube& S_cube, const arma::vec& nval, const arma::mat& B);
RcppExport SEXP _capr_log_deviation_from_diagonality_cpp(SEXP S_cubeSEXP, SEXP nvalSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type S_cube(S_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type nval(nvalSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(log_deviation_from_diagonality_cpp(S_cube, nval, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_capr_FG_cpp", (DL_FUNC) &_capr_FG_cpp, 4},
    {"_capr_FG2_cpp", (DL_FUNC) &_capr_FG2_cpp, 4},
    {"_capr_CAP_one_component_unconstrained", (DL_FUNC) &_capr_CAP_one_component_unconstrained, 7},
    {"_capr_CAP_one_component", (DL_FUNC) &_capr_CAP_one_component, 8},
    {"_capr_CAP_multi_components", (DL_FUNC) &_capr_CAP_multi_components, 9},
    {"_capr_cosine_similarity_cpp", (DL_FUNC) &_capr_cosine_similarity_cpp, 3},
    {"_capr_log_deviation_from_diagonality_cpp", (DL_FUNC) &_capr_log_deviation_from_diagonality_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_capr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
