# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FG_cpp <- function(cov_Group, L, P, M) {
    .Call('_capp_FG_cpp', PACKAGE = 'capp', cov_Group, L, P, M)
}

cap_solve <- function(X) {
    .Call('_capp_cap_solve', PACKAGE = 'capp', X)
}

