# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FG_cpp <- function(cov_cube, maxit, P, M) {
    .Call(`_capr_FG_cpp`, cov_cube, maxit, P, M)
}

CAP_one_component_unconstrained <- function(S, X, T, beta0, gamma0, max_iter = 200L, tol = 1e-6) {
    .Call(`_capr_CAP_one_component_unconstrained`, S, X, T, beta0, gamma0, max_iter, tol)
}

CAP_one_component <- function(S, X, T, beta0, gamma0, Gamma_prev, max_iter = 200L, tol = 1e-6) {
    .Call(`_capr_CAP_one_component`, S, X, T, beta0, gamma0, Gamma_prev, max_iter, tol)
}

CAP_multi_components <- function(S, X, T, K, Binit, Gammainit, orth = TRUE, max_iter = 200L, tol = 1e-6) {
    .Call(`_capr_CAP_multi_components`, S, X, T, K, Binit, Gammainit, orth, max_iter, tol)
}

#' Cosine similarity between two vectors
#'
#' Computes the cosine of the angle between \code{a} and \code{b}. Both
#' vectors must have the same length and non-zero norms.
#'
#' @noRd
cosine_similarity <- function(a, b, eps) {
    .Call(`_capr_cosine_similarity`, a, b, eps)
}

#' Log deviation from diagonality
#'
#' Computes \eqn{\sum_i n_i (\log \det \operatorname{diag}(B^\top S_i B) -
#' \log \det(B^\top S_i B))}, the criterion minimized by the FG algorithm.
#'
#' @noRd
log_deviation_from_diagonality <- function(S_cube, nval, B) {
    .Call(`_capr_log_deviation_from_diagonality`, S_cube, nval, B)
}

